# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: ${{ matrix.label }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-coding-standards.yml@3493c0c91470351828c59db5db6a18c96a11521a
    strategy:
      matrix:
        label:
          - PHP
        php:
          - '8.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
