# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: WP ${{ matrix.wp }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-integration-tests.yml@fdaa0e4a0f3cd35ecbc10059f16ca9b31466c4bf
    strategy:
      matrix:
        wp:
          # Latest 3 major versions of WordPress
          - '6.7'
          - '6.6'
          - '6.5'
        php:
          # Newest and oldest supported versions of PHP
          - '8.3'
          - '7.4'
        include:
          # Latest WordPress on PHP 8.4
          - php: '8.4'
            wp: '6.7'
          # Oldest supported version of WordPress
          - php: '7.4'
            wp: '5.8'
      fail-fast: false
    with:
      wp: ${{ matrix.wp }}
      php: ${{ matrix.php }}
      node: false
